
import pg from 'pg';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.resolve(__dirname, './.env') });

const { Pool } = pg;
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: {
    rejectUnauthorized: false
  }
});

async function runFix() {
  const client = await pool.connect();
  try {
    console.log("Starting production database fix...");

    // 1. Fix queueid not-null constraint by adding identity/sequence
    console.log("Checking and fixing 'queue' table queueid constraint...");
    await client.query(`
      DO $$
      BEGIN
        -- Check if queueid has a default value (like a sequence)
        IF NOT EXISTS (
          SELECT column_name 
          FROM information_schema.columns 
          WHERE table_name = 'queue' 
            AND column_name = 'queueid' 
            AND column_default IS NOT NULL
        ) THEN
          -- Check if we can use IDENTITY (Postgres 10+)
          BEGIN
            ALTER TABLE queue ALTER COLUMN queueid ADD GENERATED BY DEFAULT AS IDENTITY;
            RAISE NOTICE 'Added IDENTITY to queueid';
          EXCEPTION WHEN OTHERS THEN
            -- Fallback to SERIAL style sequence
            CREATE SEQUENCE IF NOT EXISTS queue_queueid_seq;
            ALTER TABLE queue ALTER COLUMN queueid SET DEFAULT nextval('queue_queueid_seq');
            PERFORM setval('queue_queueid_seq', COALESCE((SELECT MAX(queueid) FROM queue), 0) + 1);
            RAISE NOTICE 'Added Sequence fallback to queueid';
          END;
        END IF;
      END $$;
    `);

    // 2. Add missing PayMongo columns to customerpayment
    console.log("Adding missing PayMongo columns to 'customerpayment'...");
    await client.query(`
      ALTER TABLE customerpayment 
      ADD COLUMN IF NOT EXISTS reference_code VARCHAR(255),
      ADD COLUMN IF NOT EXISTS paymongo_id VARCHAR(255),
      ADD COLUMN IF NOT EXISTS checkout_url TEXT,
      ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'PHP',
      ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP,
      ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
    `);

    // 3. Add missing PayMongo columns to supplierpurchase (to match user request)
    console.log("Adding missing PayMongo columns to 'supplierpurchase'...");
    await client.query(`
      ALTER TABLE supplierpurchase 
      ADD COLUMN IF NOT EXISTS reference_code VARCHAR(255),
      ADD COLUMN IF NOT EXISTS paymongo_id VARCHAR(255),
      ADD COLUMN IF NOT EXISTS checkout_url TEXT,
      ADD COLUMN IF NOT EXISTS method VARCHAR(50),
      ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;
    `);

    console.log("Fix completed successfully!");
  } catch (err) {
    console.error("Error during fix:", err);
  } finally {
    client.release();
    await pool.end();
  }
}

runFix();
